//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetailApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Applicants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Applicants()
        {
            this.Tb_Ref = new HashSet<Tb_Ref>();
        }
    
        public int App_Id { get; set; }
        public string App_Postion { get; set; }
        public string App_First_Name { get; set; }
        public string App_Last_Name { get; set; }
        public string App_Email { get; set; }
        public string App_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ref> Tb_Ref { get; set; }
    }
}
