//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetailApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ref
    {
        public int RefId { get; set; }
        public Nullable<int> App_Id { get; set; }
        public string Ref_Name { get; set; }
        public string Ref_Phone { get; set; }
    
        public virtual Tb_Applicants Tb_Applicants { get; set; }
    }
}
